# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Trabajo final/lab1_ArtyZ7_10.xdc

# Block Designs: bd/top_gen/top_gen.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_gen || ORIG_REF_NAME==top_gen} -quiet] -quiet

# IP: bd/top_gen/ip/top_gen_processing_system7_0_0/top_gen_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_gen_processing_system7_0_0 || ORIG_REF_NAME==top_gen_processing_system7_0_0} -quiet] -quiet

# IP: bd/top_gen/ip/top_gen_control_reg_0_0/top_gen_control_reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_gen_control_reg_0_0 || ORIG_REF_NAME==top_gen_control_reg_0_0} -quiet] -quiet

# IP: bd/top_gen/ip/top_gen_ps7_0_axi_periph_0/top_gen_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_gen_ps7_0_axi_periph_0 || ORIG_REF_NAME==top_gen_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/top_gen/ip/top_gen_rst_ps7_0_100M_0/top_gen_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_gen_rst_ps7_0_100M_0 || ORIG_REF_NAME==top_gen_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/top_gen/ip/top_gen_var_clk_div_0_0/top_gen_var_clk_div_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_gen_var_clk_div_0_0 || ORIG_REF_NAME==top_gen_var_clk_div_0_0} -quiet] -quiet

# IP: bd/top_gen/ip/top_gen_ila_0_0/top_gen_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_gen_ila_0_0 || ORIG_REF_NAME==top_gen_ila_0_0} -quiet] -quiet

# IP: bd/top_gen/ip/top_gen_generator_0_0/top_gen_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_gen_generator_0_0 || ORIG_REF_NAME==top_gen_generator_0_0} -quiet] -quiet

# IP: bd/top_gen/ip/top_gen_auto_pc_0/top_gen_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_gen_auto_pc_0 || ORIG_REF_NAME==top_gen_auto_pc_0} -quiet] -quiet

# XDC: bd/top_gen/top_gen_ooc.xdc
