# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/hernan/MyS_tf1D/MyS_tf1D.cache/wt [current_project]
set_property parent.project_path /home/hernan/MyS_tf1D/MyS_tf1D.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:arty-z7-10:part0:1.1 [current_project]
set_property ip_repo_paths {
  /home/hernan/var_clk_div
  /home/hernan/MyS_tf/MyS_tf.srcs
  /home/hernan/ip_repo/control_reg_1.0
  /home/hernan/gen_ip/gen_ip.srcs
} [current_project]
set_property ip_output_repo /home/hernan/MyS_tf1D/MyS_tf1D.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/hernan/MyS_tf1D/MyS_tf1D.srcs/sources_1/imports/src/clk_div.vhd
  /home/hernan/MyS_tf1D/MyS_tf1D.srcs/sources_1/imports/src/pwm.vhd
  /home/hernan/MyS_tf1D/MyS_tf1D.srcs/sources_1/imports/src/sine.vhd
  /home/hernan/MyS_tf1D/MyS_tf1D.srcs/sources_1/imports/src/generator.vhd
  /home/hernan/MyS_tf1D/MyS_tf1D.srcs/sources_1/new/ila_generador.vhd
  /home/hernan/MyS_tf1D/MyS_tf1D.srcs/sources_1/bd/top_gen/hdl/top_gen_wrapper.vhd
}
add_files /home/hernan/MyS_tf1D/MyS_tf1D.srcs/sources_1/bd/top_gen/top_gen.bd
set_property used_in_implementation false [get_files -all /home/hernan/MyS_tf1D/MyS_tf1D.srcs/sources_1/bd/top_gen/ip/top_gen_processing_system7_0_0/top_gen_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/hernan/MyS_tf1D/MyS_tf1D.srcs/sources_1/bd/top_gen/ip/top_gen_rst_ps7_0_100M_0/top_gen_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/hernan/MyS_tf1D/MyS_tf1D.srcs/sources_1/bd/top_gen/ip/top_gen_rst_ps7_0_100M_0/top_gen_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/hernan/MyS_tf1D/MyS_tf1D.srcs/sources_1/bd/top_gen/ip/top_gen_rst_ps7_0_100M_0/top_gen_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/hernan/MyS_tf1D/MyS_tf1D.srcs/sources_1/bd/top_gen/ip/top_gen_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/hernan/MyS_tf1D/MyS_tf1D.srcs/sources_1/bd/top_gen/ip/top_gen_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/hernan/MyS_tf1D/MyS_tf1D.srcs/sources_1/bd/top_gen/ip/top_gen_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/hernan/MyS_tf1D/MyS_tf1D.srcs/sources_1/bd/top_gen/ip/top_gen_ila_0_0/top_gen_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all {{/home/hernan/MyS_tf1D/MyS_tf1D.srcs/sources_1/bd/top_gen/ip/top_gen_generator_0_0/constrs_1/imports/Trabajo final/lab1_ArtyZ7_10.xdc}}]
set_property used_in_implementation false [get_files -all /home/hernan/MyS_tf1D/MyS_tf1D.srcs/sources_1/bd/top_gen/ip/top_gen_auto_pc_0/top_gen_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hernan/MyS_tf1D/MyS_tf1D.srcs/sources_1/bd/top_gen/top_gen_ooc.xdc]

read_ip -quiet /home/hernan/MyS_tf1D/MyS_tf1D.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all /home/hernan/MyS_tf1D/MyS_tf1D.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/hernan/MyS_tf1D/MyS_tf1D.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/hernan/MyS_tf1D/MyS_tf1D.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/hernan/MyS_tf1D/MyS_tf1D.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{/home/hernan/MyS_tf1D/MyS_tf1D.srcs/constrs_1/imports/Trabajo final/lab1_ArtyZ7_10.xdc}}
set_property used_in_implementation false [get_files {{/home/hernan/MyS_tf1D/MyS_tf1D.srcs/constrs_1/imports/Trabajo final/lab1_ArtyZ7_10.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top_gen_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_gen_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_gen_wrapper_utilization_synth.rpt -pb top_gen_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
